using NetDaemon.Common;
using NetDaemon.Common.Fluent;

namespace Netdaemon.Generated.Extensions
{
    public static partial class EntityExtension
    {
        public static SwitchEntities SwitchEx(this NetDaemonApp app) => new SwitchEntities(app);
        public static AutomationEntities AutomationEx(this NetDaemonApp app) => new AutomationEntities(app);
        public static LightEntities LightEx(this NetDaemonApp app) => new LightEntities(app);
        public static ScriptEntities ScriptEx(this NetDaemonApp app) => new ScriptEntities(app);
        public static MediaPlayerEntities MediaPlayerEx(this NetDaemonApp app) => new MediaPlayerEntities(app);
        public static CameraEntities CameraEx(this NetDaemonApp app) => new CameraEntities(app);
    }

    public partial class SwitchEntities
    {
        private readonly NetDaemonApp _app;
        public SwitchEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public IEntity WarehouseAlarmState => _app.Entity("switch.warehouse_alarm_state");
        public IEntity SmartlampNightMode => _app.Entity("switch.smartlamp_night_mode");
        public IEntity WarehouseRadiator => _app.Entity("switch.warehouse_radiator");
        public IEntity ArcadeCabinetMarquee => _app.Entity("switch.arcade_cabinet_marquee");
        public IEntity Chargers => _app.Entity("switch.chargers");
        public IEntity CrystalStones => _app.Entity("switch.crystal_stones");
        public IEntity LivingRoomBack => _app.Entity("switch.living_room_back");
        public IEntity Generic => _app.Entity("switch.generic");
        public IEntity NetdaemonWifi2IrAppTvPhilips => _app.Entity("switch.netdaemon_wifi2_ir_app_tv_philips");
        public IEntity LightStringPower => _app.Entity("switch.light_string_power");
        public IEntity NetdaemonWifi2IrAppClimate => _app.Entity("switch.netdaemon_wifi2_ir_app_climate");
        public IEntity WarehouseFloodLight => _app.Entity("switch.warehouse_flood_light");
        public IEntity ArcadeCabinetPower => _app.Entity("switch.arcade_cabinet_power");
        public IEntity E3dPrinterPower => _app.Entity("switch.3d_printer_power");
        public IEntity MediaPcPower => _app.Entity("switch.media_pc_power");
        public IEntity BoilerPower => _app.Entity("switch.boiler_power");
        public IEntity NetdaemonWifi2IrAppReceiver => _app.Entity("switch.netdaemon_wifi2_ir_app_receiver");
        public IEntity LivingRoomFront => _app.Entity("switch.living_room_front");
        public IEntity BedHeadbackPower => _app.Entity("switch.bed_headback_power");
        public IEntity NetdaemonWifi2IrAppPartnerTv => _app.Entity("switch.netdaemon_wifi2_ir_app_partner_tv");
        public IEntity CamerasPower => _app.Entity("switch.cameras_power");
        public IEntity ColorLightStringPower => _app.Entity("switch.color_light_string_power");
        public IEntity WarehouseFan => _app.Entity("switch.warehouse_fan");
        public IEntity NetdaemonWifi2IrAppTvLg => _app.Entity("switch.netdaemon_wifi2_ir_app_tv_lg");
        public IEntity SmartlampAutoSleep => _app.Entity("switch.smartlamp_auto_sleep");
        public IEntity WarehouseLight => _app.Entity("switch.warehouse_light");
        public IEntity ExtraCable => _app.Entity("switch.extra_cable");
        public IEntity CandlesPower => _app.Entity("switch.candles_power");
    }

    public partial class AutomationEntities
    {
        private readonly NetDaemonApp _app;
        public AutomationEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public IEntity LcdSetLivingRoomTemp => _app.Entity("automation.lcd_set_living_room_temp");
        public IEntity GoingToSleep => _app.Entity("automation.going_to_sleep");
        public IEntity E30MinPreCandleLighting => _app.Entity("automation.30_min_pre_candle_lighting");
        public IEntity LightStringColorBrightnessChange => _app.Entity("automation.light_string_color_brightness_change");
        public IEntity AssistantOn => _app.Entity("automation.assistant_on");
        public IEntity PlayMusic => _app.Entity("automation.play_music");
        public IEntity ReceiverVolumeLevelChange => _app.Entity("automation.receiver_volume_level_change");
        public IEntity Automation104 => _app.Entity("automation.automation_104");
        public IEntity SetLightTheme => _app.Entity("automation.set_light_theme");
        public IEntity LgTvOffActions => _app.Entity("automation.lg_tv_off_actions");
        public IEntity SetTurnOnMediaPcOnHouseLeave => _app.Entity("automation.set_turn_on_media_pc_on_house_leave");
        public IEntity KodisPlayModeSetSingle => _app.Entity("automation.kodis_play_mode_set_single");
        public IEntity LgtvPowerSwitchedOn => _app.Entity("automation.lgtv_power_switched_on");
        public IEntity WarehousePowerUp => _app.Entity("automation.warehouse_power_up");
        public IEntity DoneActivityUsingWarehouse => _app.Entity("automation.done_activity_using_warehouse");
        public IEntity TurnOnAutoClimateInBedRoom => _app.Entity("automation.turn_on_auto_climate_in_bed_room");
        public IEntity ActivityPlayArcadeMachine => _app.Entity("automation.activity_play_arcade_machine");
        public IEntity GlobalVolumeDown => _app.Entity("automation.global_volume_down");
        public IEntity PhilipsAmbilightSwitchedOff => _app.Entity("automation.philips_ambilight_switched_off");
        public IEntity CandleLightingToday => _app.Entity("automation.candle_lighting_today");
        public IEntity Automation76 => _app.Entity("automation.automation_76");
        public IEntity PhilipsAmbilightSwitchedOffInvalid => _app.Entity("automation.philips_ambilight_switched_off_invalid");
        public IEntity MopidyPowerOn => _app.Entity("automation.mopidy_power_on");
        public IEntity Automation64 => _app.Entity("automation.automation_64");
        public IEntity LikeDislikeTrackRequest => _app.Entity("automation.like_dislike_track_request");
        public IEntity Automation2 => _app.Entity("automation.automation_2");
        public IEntity ProfileEnabled => _app.Entity("automation.profile_enabled");
        public IEntity BedroomPowerSaveDisabled => _app.Entity("automation.bedroom_power_save_disabled");
        public IEntity NeonSignScenarioDelayChanged => _app.Entity("automation.neon_sign_scenario_delay_changed");
        public IEntity BoilerTimerSet => _app.Entity("automation.boiler_timer_set");
        public IEntity LgtvPowerSwitchedOff => _app.Entity("automation.lgtv_power_switched_off");
        public IEntity TriplePanelRightRight => _app.Entity("automation.triple_panel_right_right");
        public IEntity DoActivityRequest => _app.Entity("automation.do_activity_request");
        public IEntity KodiPlaying => _app.Entity("automation.kodi_playing");
        public IEntity Automation101 => _app.Entity("automation.automation_101");
        public IEntity BedroomPowerSaveArcademarqueeOn => _app.Entity("automation.bedroom_power_save_arcademarquee_on");
        public IEntity Automation5 => _app.Entity("automation.automation_5");
        public IEntity MopidyVolume => _app.Entity("automation.mopidy_volume");
        public IEntity Automation75 => _app.Entity("automation.automation_75");
        public IEntity MediaProfileInvalidChange => _app.Entity("automation.media_profile_invalid_change");
        public IEntity Automation136 => _app.Entity("automation.automation_136");
        public IEntity ActivitySleep => _app.Entity("automation.activity_sleep");
        public IEntity HassTheme => _app.Entity("automation.hass_theme");
        public IEntity NeonSignGreenChanged => _app.Entity("automation.neon_sign_green_changed");
        public IEntity SetBedHeadbackScenarioSelector => _app.Entity("automation.set_bed_headback_scenario_selector");
        public IEntity TabletPowerLow => _app.Entity("automation.tablet_power_low");
        public IEntity LgtvVolumeSetter => _app.Entity("automation.lgtv_volume_setter");
        public IEntity InfluxFolderSize => _app.Entity("automation.influx_folder_size");
        public IEntity ActivityGoingToWarehouse => _app.Entity("automation.activity_going_to_warehouse");
        public IEntity KodisPlayModeSetSurround => _app.Entity("automation.kodis_play_mode_set_surround");
        public IEntity BedHeadbackScenarioSet => _app.Entity("automation.bed_headback_scenario_set");
        public IEntity ProjectorPowerSwitchedOn => _app.Entity("automation.projector_power_switched_on");
        public IEntity Automation107 => _app.Entity("automation.automation_107");
        public IEntity ActivityCinemaAsBackground => _app.Entity("automation.activity_cinema_as_background");
        public IEntity Automation4 => _app.Entity("automation.automation_4");
        public IEntity SetLightStringScenarioSelector => _app.Entity("automation.set_light_string_scenario_selector");
        public IEntity AssistantVolumeChanged => _app.Entity("automation.assistant_volume_changed");
        public IEntity InfinityCubeBlueChanged => _app.Entity("automation.infinity_cube_blue_changed");
        public IEntity ResetWakeupFlag => _app.Entity("automation.reset_wakeup_flag");
        public IEntity PhilipsPowerSwitchedOff => _app.Entity("automation.philips_power_switched_off");
        public IEntity ClimateControlActionRequest => _app.Entity("automation.climate_control_action_request");
        public IEntity LgtvVolumeTracker => _app.Entity("automation.lgtv_volume_tracker");
        public IEntity BulkControlMusicSwitchedOn => _app.Entity("automation.bulk_control_music_switched_on");
        public IEntity Automation143 => _app.Entity("automation.automation_143");
        public IEntity NeonSignPowerChanged => _app.Entity("automation.neon_sign_power_changed");
        public IEntity KeepChargersOn => _app.Entity("automation.keep_chargers_on");
        public IEntity MediaPcVolumeSetter => _app.Entity("automation.media_pc_volume_setter");
        public IEntity BedHeadbackGreenChanged => _app.Entity("automation.bed_headback_green_changed");
        public IEntity KodisPlayFileSet => _app.Entity("automation.kodis_play_file_set");
        public IEntity ReceiverVolLevelSetter => _app.Entity("automation.receiver_vol_level_setter");
        public IEntity Automation96 => _app.Entity("automation.automation_96");
        public IEntity MediaPcVideoOutputSet => _app.Entity("automation.media_pc_video_output_set");
        public IEntity HttpLsxLocationUpdate => _app.Entity("automation.http_lsx_location_update");
        public IEntity SunsetWalkIn15Mins => _app.Entity("automation.sunset_walk_in_15_mins");
        public IEntity TvSourceSet2 => _app.Entity("automation.tv_source_set_2");
        public IEntity InfinityCubeGreenChanged => _app.Entity("automation.infinity_cube_green_changed");
        public IEntity Automation98 => _app.Entity("automation.automation_98");
        public IEntity MediaPcTvVideoProfileTracker => _app.Entity("automation.media_pc_tv_video_profile_tracker");
        public IEntity LeaveTimeForReading => _app.Entity("automation.leave_time_for_reading");
        public IEntity SmartphonePowerLow => _app.Entity("automation.smartphone_power_low");
        public IEntity ArcadeCabinetPowerChange => _app.Entity("automation.arcade_cabinet_power_change");
        public IEntity DualPanelLeft => _app.Entity("automation.dual_panel_left");
        public IEntity DualPanelRightLeft => _app.Entity("automation.dual_panel_right_left");
        public IEntity SetInfinityCubeBlendingSelector => _app.Entity("automation.set_infinity_cube_blending_selector");
        public IEntity InfluxFolderSizeRecieve => _app.Entity("automation.influx_folder_size_recieve");
        public IEntity GamesCornerNeonModeSet => _app.Entity("automation.games_corner_neon_mode_set");
        public IEntity SpeakWeather => _app.Entity("automation.speak_weather");
        public IEntity BedroomPowerSaveEnabled => _app.Entity("automation.bedroom_power_save_enabled");
        public IEntity KodisPlayModeSetReciever => _app.Entity("automation.kodis_play_mode_set_reciever");
        public IEntity TriplePanelLeftLeft => _app.Entity("automation.triple_panel_left_left");
        public IEntity BedHeadbackScenarioDelayChange => _app.Entity("automation.bed_headback_scenario_delay_change");
        public IEntity Automation70 => _app.Entity("automation.automation_70");
        public IEntity DualPanelRightRight => _app.Entity("automation.dual_panel_right_right");
        public IEntity LightStringColorBrightnessChanged => _app.Entity("automation.light_string_color_brightness_changed");
        public IEntity LightStringStartPointChanged => _app.Entity("automation.light_string_start_point_changed");
        public IEntity SetInfinityCubeScenarioSelector => _app.Entity("automation.set_infinity_cube_scenario_selector");
        public IEntity LgtvPowerSensedOn => _app.Entity("automation.lgtv_power_sensed_on");
        public IEntity Automation141 => _app.Entity("automation.automation_141");
        public IEntity MediaPcVideoProfileSet => _app.Entity("automation.media_pc_video_profile_set");
        public IEntity AssistantWakeupMessageHandler => _app.Entity("automation.assistant_wakeup_message_handler");
        public IEntity ArcadeCabinetAmbientSoundSet => _app.Entity("automation.arcade_cabinet_ambient_sound_set");
        public IEntity MediaPcVolumeChanged => _app.Entity("automation.media_pc_volume_changed");
        public IEntity TriplePanelMiddleLeft => _app.Entity("automation.triple_panel_middle_left");
        public IEntity ProjectorBackgroundOff => _app.Entity("automation.projector_background_off");
        public IEntity BedroomPowerSaveHeadbackOn => _app.Entity("automation.bedroom_power_save_headback_on");
        public IEntity SmartLampScenarioDelayChanged => _app.Entity("automation.smart_lamp_scenario_delay_changed");
        public IEntity DoneActivityRequest => _app.Entity("automation.done_activity_request");
        public IEntity LightStringEndPointChange2 => _app.Entity("automation.light_string_end_point_change_2");
        public IEntity SetGamesCornerNeonModeSelector => _app.Entity("automation.set_games_corner_neon_mode_selector");
        public IEntity TrafficThresholdChanged => _app.Entity("automation.traffic_threshold_changed");
        public IEntity GlobalMediaPlaypause => _app.Entity("automation.global_media_playpause");
        public IEntity WarehouseDoorSensorArmed => _app.Entity("automation.warehouse_door_sensor_armed");
        public IEntity LightStringScenarioSet2 => _app.Entity("automation.light_string_scenario_set_2");
        public IEntity TurnOnAutoClimateInLivingRoom => _app.Entity("automation.turn_on_auto_climate_in_living_room");
        public IEntity ActivityPlayPcOnTv => _app.Entity("automation.activity_play_pc_on_tv");
        public IEntity LikeDislikeTrack => _app.Entity("automation.like_dislike_track");
        public IEntity TriplePanelLeft => _app.Entity("automation.triple_panel_left");
        public IEntity Automation67 => _app.Entity("automation.automation_67");
        public IEntity GlobalVolumeUp => _app.Entity("automation.global_volume_up");
        public IEntity PhilipsAmbilightSwitchedOnInvalid => _app.Entity("automation.philips_ambilight_switched_on_invalid");
        public IEntity InfinityCubeRedChanged => _app.Entity("automation.infinity_cube_red_changed");
        public IEntity AssistantOff => _app.Entity("automation.assistant_off");
        public IEntity ActivityWatchCableTv => _app.Entity("automation.activity_watch_cable_tv");
        public IEntity LightStringStartPointChanged2 => _app.Entity("automation.light_string_start_point_changed_2");
        public IEntity MediaPcTvVideoProfileSetter => _app.Entity("automation.media_pc_tv_video_profile_setter");
        public IEntity ForceScriptWakingUp => _app.Entity("automation.force_script_waking_up");
        public IEntity ProjectorPowerSwitchedOff => _app.Entity("automation.projector_power_switched_off");
        public IEntity Automation72 => _app.Entity("automation.automation_72");
        public IEntity ArcadeCabinetScenarioSet => _app.Entity("automation.arcade_cabinet_scenario_set");
        public IEntity TriplePanelRightLeft => _app.Entity("automation.triple_panel_right_left");
        public IEntity MopidyShuffleOff => _app.Entity("automation.mopidy_shuffle_off");
        public IEntity Automation140 => _app.Entity("automation.automation_140");
        public IEntity Automation66 => _app.Entity("automation.automation_66");
        public IEntity TvSourceSet => _app.Entity("automation.tv_source_set");
        public IEntity Automation65 => _app.Entity("automation.automation_65");
        public IEntity LightStringScenarioDelayChanged => _app.Entity("automation.light_string_scenario_delay_changed");
        public IEntity Automation135 => _app.Entity("automation.automation_135");
        public IEntity MediaCommandRequest => _app.Entity("automation.media_command_request");
        public IEntity BedroomPowerSaveColorLightstringOn => _app.Entity("automation.bedroom_power_save_color_lightstring_on");
        public IEntity ArcadeCabinetPowerChanged => _app.Entity("automation.arcade_cabinet_power_changed");
        public IEntity Automation74 => _app.Entity("automation.automation_74");
        public IEntity KodiLibraryRefresh => _app.Entity("automation.kodi_library_refresh");
        public IEntity Automation71 => _app.Entity("automation.automation_71");
        public IEntity LightStringScenarioDelayChange => _app.Entity("automation.light_string_scenario_delay_change");
        public IEntity Automation106 => _app.Entity("automation.automation_106");
        public IEntity BedroomPowerSaveCandlesOn => _app.Entity("automation.bedroom_power_save_candles_on");
        public IEntity BedHeadbackScenarioDelayChanged => _app.Entity("automation.bed_headback_scenario_delay_changed");
        public IEntity Automation156 => _app.Entity("automation.automation_156");
        public IEntity TriplePanelRightMiddle => _app.Entity("automation.triple_panel_right_middle");
        public IEntity Automation99 => _app.Entity("automation.automation_99");
        public IEntity TriplePanelMiddleRight => _app.Entity("automation.triple_panel_middle_right");
        public IEntity WarehousePowerDown => _app.Entity("automation.warehouse_power_down");
        public IEntity SpeakMopidyRemoveUnfavored => _app.Entity("automation.speak_mopidy_remove_unfavored");
        public IEntity Ac1AutoModeProcessor => _app.Entity("automation.ac1_auto_mode_processor");
        public IEntity ActivityPlayThePlaystation => _app.Entity("automation.activity_play_the_playstation");
        public IEntity DualPanelRight => _app.Entity("automation.dual_panel_right");
        public IEntity LgtvVolumeChanged => _app.Entity("automation.lgtv_volume_changed");
        public IEntity SmartLampBlueChanged => _app.Entity("automation.smart_lamp_blue_changed");
        public IEntity ProjectorBackgroundOn => _app.Entity("automation.projector_background_on");
        public IEntity SetArcadeCabinetAttractModeSelector => _app.Entity("automation.set_arcade_cabinet_attract_mode_selector");
        public IEntity ArcadeCabinetScenarioDelayChanged => _app.Entity("automation.arcade_cabinet_scenario_delay_changed");
        public IEntity ArcadeCabinetScenarioDelayChange => _app.Entity("automation.arcade_cabinet_scenario_delay_change");
        public IEntity BoilerTimerVoiceUpdate => _app.Entity("automation.boiler_timer_voice_update");
        public IEntity DoneActivityPlayingTheArcadeMachine => _app.Entity("automation.done_activity_playing_the_arcade_machine");
        public IEntity ActivityGoingToNeedAShower => _app.Entity("automation.activity_going_to_need_a_shower");
        public IEntity LightStringScenarioDelayChange2 => _app.Entity("automation.light_string_scenario_delay_change_2");
        public IEntity DoneActivityUsingTheProfile => _app.Entity("automation.done_activity_using_the_profile");
        public IEntity SetTurnOffMediaPcOnHouseLeave => _app.Entity("automation.set_turn_off_media_pc_on_house_leave");
        public IEntity ReceiverInputSoundChange => _app.Entity("automation.receiver_input_sound_change");
        public IEntity ProfileDisabled => _app.Entity("automation.profile_disabled");
        public IEntity InfinityCubeScenarioDelayChange => _app.Entity("automation.infinity_cube_scenario_delay_change");
        public IEntity NeonSignPowerChange => _app.Entity("automation.neon_sign_power_change");
        public IEntity LgtvPowerSensedOff => _app.Entity("automation.lgtv_power_sensed_off");
        public IEntity SetHouseLightThemeSelector => _app.Entity("automation.set_house_light_theme_selector");
        public IEntity KodiVolumeSetter => _app.Entity("automation.kodi_volume_setter");
        public IEntity Automation145 => _app.Entity("automation.automation_145");
        public IEntity ReceiverVolLevelTracker => _app.Entity("automation.receiver_vol_level_tracker");
        public IEntity ShowerNoMovement => _app.Entity("automation.shower_no_movement");
        public IEntity AssistantVoiceCommandsOn => _app.Entity("automation.assistant_voice_commands_on");
        public IEntity Automation100 => _app.Entity("automation.automation_100");
        public IEntity NeonSignScenarioDelayChange => _app.Entity("automation.neon_sign_scenario_delay_change");
        public IEntity InfinityCubeScenarioSet => _app.Entity("automation.infinity_cube_scenario_set");
        public IEntity SetArcadeCabinetAmbientSoundSelector => _app.Entity("automation.set_arcade_cabinet_ambient_sound_selector");
        public IEntity BedroomPowerSaveNoMovement => _app.Entity("automation.bedroom_power_save_no_movement");
        public IEntity BedroomPowerSaveMovement => _app.Entity("automation.bedroom_power_save_movement");
        public IEntity InfinityCubeNightMovement => _app.Entity("automation.infinity_cube_night_movement");
        public IEntity BedHeadbackPowerChanged => _app.Entity("automation.bed_headback_power_changed");
        public IEntity TriplePanelLeftMiddle => _app.Entity("automation.triple_panel_left_middle");
        public IEntity LcdBacklightModeSet => _app.Entity("automation.lcd_backlight_mode_set");
        public IEntity ArcadeCabinetBlueChanged => _app.Entity("automation.arcade_cabinet_blue_changed");
        public IEntity VoiceCommandAbort => _app.Entity("automation.voice_command_abort");
        public IEntity AssistantVoiceCommandsOff => _app.Entity("automation.assistant_voice_commands_off");
        public IEntity TriplePanelMiddle => _app.Entity("automation.triple_panel_middle");
        public IEntity TriplePanelRight => _app.Entity("automation.triple_panel_right");
        public IEntity Automation133 => _app.Entity("automation.automation_133");
        public IEntity ArcadeCabinetGreenChanged => _app.Entity("automation.arcade_cabinet_green_changed");
        public IEntity SetLightStringScenarioSelector2 => _app.Entity("automation.set_light_string_scenario_selector_2");
        public IEntity LightStringStartPointChange => _app.Entity("automation.light_string_start_point_change");
        public IEntity MediaPcAudioOutputSet => _app.Entity("automation.media_pc_audio_output_set");
        public IEntity ActivityLeaveTheHouse => _app.Entity("automation.activity_leave_the_house");
        public IEntity NeonSignScenarioSet => _app.Entity("automation.neon_sign_scenario_set");
        public IEntity LightStringEndPointChange => _app.Entity("automation.light_string_end_point_change");
        public IEntity KodisPlayModeSetTv2 => _app.Entity("automation.kodis_play_mode_set_tv_2");
        public IEntity InfinityCubeScenarioDelayChanged => _app.Entity("automation.infinity_cube_scenario_delay_changed");
        public IEntity Automation63 => _app.Entity("automation.automation_63");
        public IEntity SmartLampScenarioSet => _app.Entity("automation.smart_lamp_scenario_set");
        public IEntity KodisPlayModeSetDual => _app.Entity("automation.kodis_play_mode_set_dual");
        public IEntity Automation68 => _app.Entity("automation.automation_68");
        public IEntity Wirelessmotionsesnsor9b76ToShowerMotionAdapter => _app.Entity("automation.wirelessmotionsesnsor_9b76_to_shower_motion_adapter");
        public IEntity KodiVolumeTracker => _app.Entity("automation.kodi_volume_tracker");
        public IEntity DualPanelLeftRight => _app.Entity("automation.dual_panel_left_right");
        public IEntity ActivityWatchAMovie => _app.Entity("automation.activity_watch_a_movie");
        public IEntity BoilerTimerStatusSetter => _app.Entity("automation.boiler_timer_status_setter");
        public IEntity Automation155 => _app.Entity("automation.automation_155");
        public IEntity BedHeadbackNightModeOff => _app.Entity("automation.bed_headback_night_mode_off");
        public IEntity ArcadeCabinetVolumeChange => _app.Entity("automation.arcade_cabinet_volume_change");
        public IEntity LcdDateTimeUpdater => _app.Entity("automation.lcd_date_time_updater");
        public IEntity SmartlampToBedroomMotionAdapter => _app.Entity("automation.smartlamp_to_bedroom_motion_adapter");
        public IEntity BedHeadbackBlueChanged => _app.Entity("automation.bed_headback_blue_changed");
        public IEntity PhilipsLaptopPowerSensedOff => _app.Entity("automation.philips_laptop_power_sensed_off");
        public IEntity MopidyShuffleOn => _app.Entity("automation.mopidy_shuffle_on");
        public IEntity BedHeadbackPowerChange => _app.Entity("automation.bed_headback_power_change");
        public IEntity LightStringEndPointChanged2 => _app.Entity("automation.light_string_end_point_changed_2");
        public IEntity AssistantPowerOn => _app.Entity("automation.assistant_power_on");
        public IEntity WirelessmotionsesnsorAd0dToBedroomMotionAdapter => _app.Entity("automation.wirelessmotionsesnsor_ad0d_to_bedroom_motion_adapter");
        public IEntity ReceiverPowerSwitchChange => _app.Entity("automation.receiver_power_switch_change");
        public IEntity Ac2AutoModeProcessor => _app.Entity("automation.ac2_auto_mode_processor");
        public IEntity KeepExtensionCableOn => _app.Entity("automation.keep_extension_cable_on");
        public IEntity SmartLampScenarioDelayChange => _app.Entity("automation.smart_lamp_scenario_delay_change");
        public IEntity DualPanelLeftLeft => _app.Entity("automation.dual_panel_left_left");
        public IEntity WarehouseDoorOpened => _app.Entity("automation.warehouse_door_opened");
        public IEntity DoneActivitySleep => _app.Entity("automation.done_activity_sleep");
        public IEntity SetNeonSignScenarioSelector => _app.Entity("automation.set_neon_sign_scenario_selector");
        public IEntity Automation105 => _app.Entity("automation.automation_105");
        public IEntity BedroomPowerSaveLightstringOn => _app.Entity("automation.bedroom_power_save_lightstring_on");
        public IEntity WakeupWordDetectedMuteMedias => _app.Entity("automation.wakeup_word_detected_mute_medias");
        public IEntity BedHeadbackLampRedChanged => _app.Entity("automation.bed_headback_lamp_red_changed");
        public IEntity LightStringEndPointChanged => _app.Entity("automation.light_string_end_point_changed");
        public IEntity NeonSignLampRedChanged => _app.Entity("automation.neon_sign_lamp_red_changed");
        public IEntity BedroomPowerSaveArcadergbOn => _app.Entity("automation.bedroom_power_save_arcadergb_on");
        public IEntity MopidyPlayPlaylistSet => _app.Entity("automation.mopidy_play_playlist_set");
        public IEntity ArcadeCabinetLampRedChanged => _app.Entity("automation.arcade_cabinet_lamp_red_changed");
        public IEntity TriplePanelMiddleMiddle => _app.Entity("automation.triple_panel_middle_middle");
        public IEntity Automation61 => _app.Entity("automation.automation_61");
        public IEntity NeonSignBlueChanged => _app.Entity("automation.neon_sign_blue_changed");
        public IEntity LightStringBrightnessChange => _app.Entity("automation.light_string_brightness_change");
        public IEntity PhilipsAmbilightSwitchedOn => _app.Entity("automation.philips_ambilight_switched_on");
        public IEntity Automation62 => _app.Entity("automation.automation_62");
        public IEntity LcdSetOutsideTemp => _app.Entity("automation.lcd_set_outside_temp");
        public IEntity PhilipsPowerSwitchedOn => _app.Entity("automation.philips_power_switched_on");
        public IEntity ApproachingHomeActions => _app.Entity("automation.approaching_home_actions");
        public IEntity UnhandledNonRecognizedIntentUnmuteMedias => _app.Entity("automation.unhandled_non_recognized_intent_unmute_medias");
        public IEntity SetArcadeCabinetScenarioSelector => _app.Entity("automation.set_arcade_cabinet_scenario_selector");
        public IEntity ActivityUseCinema => _app.Entity("automation.activity_use_cinema");
        public IEntity Automation132 => _app.Entity("automation.automation_132");
        public IEntity LightStringStartPointChange2 => _app.Entity("automation.light_string_start_point_change_2");
        public IEntity BedHeadbackNightMovement => _app.Entity("automation.bed_headback_night_movement");
        public IEntity SmartLampGreenChanged => _app.Entity("automation.smart_lamp_green_changed");
        public IEntity SetSmartLampScenarioSelector => _app.Entity("automation.set_smart_lamp_scenario_selector");
        public IEntity Automation73 => _app.Entity("automation.automation_73");
        public IEntity SpeakMopidyMarkFavored => _app.Entity("automation.speak_mopidy_mark_favored");
        public IEntity AutoEveningLights => _app.Entity("automation.auto_evening_lights");
        public IEntity SpeakMopidyMarkUnfavored => _app.Entity("automation.speak_mopidy_mark_unfavored");
        public IEntity LightStringBrightnessChanged => _app.Entity("automation.light_string_brightness_changed");
        public IEntity KodisPlayFolderSet => _app.Entity("automation.kodis_play_folder_set");
        public IEntity Automation137 => _app.Entity("automation.automation_137");
        public IEntity MediaPcVolumeTracker => _app.Entity("automation.media_pc_volume_tracker");
        public IEntity MediaCommand => _app.Entity("automation.media_command");
        public IEntity PhilipsLaptopPowerSensedOn => _app.Entity("automation.philips_laptop_power_sensed_on");
        public IEntity Automation142 => _app.Entity("automation.automation_142");
        public IEntity Automation3 => _app.Entity("automation.automation_3");
        public IEntity AssistantPowerOff => _app.Entity("automation.assistant_power_off");
        public IEntity Automation134 => _app.Entity("automation.automation_134");
        public IEntity InfinityCubeNightModeOff => _app.Entity("automation.infinity_cube_night_mode_off");
        public IEntity BulkControlTvNewsSwitchedOn => _app.Entity("automation.bulk_control_tv_news_switched_on");
        public IEntity Automation144 => _app.Entity("automation.automation_144");
        public IEntity LeavingHomeActions => _app.Entity("automation.leaving_home_actions");
        public IEntity PlayMusicRequest => _app.Entity("automation.play_music_request");
        public IEntity SmartlampPowerstate => _app.Entity("automation.smartlamp_powerstate");
        public IEntity LightStringScenarioSet => _app.Entity("automation.light_string_scenario_set");
        public IEntity TriplePanelLeftRight => _app.Entity("automation.triple_panel_left_right");
        public IEntity SetLightThemeRequest => _app.Entity("automation.set_light_theme_request");
        public IEntity ArcadeCabinetAttractModeSet => _app.Entity("automation.arcade_cabinet_attract_mode_set");
        public IEntity LcdSetBedRoomTemp => _app.Entity("automation.lcd_set_bed_room_temp");
        public IEntity VoiceCommandApprove => _app.Entity("automation.voice_command_approve");
        public IEntity Automation69 => _app.Entity("automation.automation_69");
        public IEntity SayTime => _app.Entity("automation.say_time");
        public IEntity KodisPlayModeSetTv => _app.Entity("automation.kodis_play_mode_set_tv");
        public IEntity BedroomPowerSaveNeonOn => _app.Entity("automation.bedroom_power_save_neon_on");
        public IEntity LightStringScenarioDelayChanged2 => _app.Entity("automation.light_string_scenario_delay_changed_2");
        public IEntity AssistantVoiceOn => _app.Entity("automation.assistant_voice_on");
        public IEntity ArcadeCabinetVolumeChanged => _app.Entity("automation.arcade_cabinet_volume_changed");
        public IEntity InfinityCubeBlendingSet => _app.Entity("automation.infinity_cube_blending_set");
        public IEntity Automation97 => _app.Entity("automation.automation_97");
        public IEntity InfluxFolderSizeGet => _app.Entity("automation.influx_folder_size_get");
        public IEntity MopidyPowerOff => _app.Entity("automation.mopidy_power_off");
        public IEntity TurnOnAutoClimateInHouse => _app.Entity("automation.turn_on_auto_climate_in_house");
        public IEntity SmartLampRedChanged => _app.Entity("automation.smart_lamp_red_changed");
        public IEntity WakingUp => _app.Entity("automation.waking_up");
    }

    public partial class LightEntities
    {
        private readonly NetDaemonApp _app;
        public LightEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public IEntity SmartlampLight => _app.Entity("light.smartlamp_light");
        public IEntity E408fb272C9cfe7cd => _app.Entity("light.408fb272_c9cfe7cd");
        public IEntity ArcadeCabinetRgb => _app.Entity("light.arcade_cabinet_rgb");
        public IEntity E3c93d829A6a8fd92 => _app.Entity("light.3c93d829_a6a8fd92");
        public IEntity Eccef44127e0e6b2 => _app.Entity("light.eccef441_27e0e6b2");
        public IEntity NeonSignRgb => _app.Entity("light.neon_sign_rgb");
        public IEntity InfinityCubeLight => _app.Entity("light.infinity_cube_light");
        public IEntity BedHeadbackRgb => _app.Entity("light.bed_headback_rgb");
        public IEntity E3dPrinterLight => _app.Entity("light.3d_printer_light");
    }

    public partial class ScriptEntities
    {
        private readonly NetDaemonApp _app;
        public ScriptEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public IEntity BulkLaunchArcadeCabinetMarquee => _app.Entity("script.bulk_launch_arcade_cabinet_marquee");
        public IEntity NeonsignSavepoint1 => _app.Entity("script.neonsign_savepoint1");
        public IEntity TvPcEnableTvProcess => _app.Entity("script.tv_pc_enable_tv_process");
        public IEntity BedroomPowerSaveOn => _app.Entity("script.bedroom_power_save_on");
        public IEntity InfinitycubeSavepoint1 => _app.Entity("script.infinitycube_savepoint1");
        public IEntity SmartlampLoadpoint2 => _app.Entity("script.smartlamp_loadpoint2");
        public IEntity RhasspyRestart => _app.Entity("script.rhasspy_restart");
        public IEntity ProfileEnable => _app.Entity("script.profile_enable");
        public IEntity AssistantDoactivityWarehouse => _app.Entity("script.assistant_doactivity_warehouse");
        public IEntity Rl4mpPresetLowerleft => _app.Entity("script.rl4mp_preset_lowerleft");
        public IEntity Ac2FanSetup => _app.Entity("script.ac2_fan_setup");
        public IEntity TvGamingConsoleDisable => _app.Entity("script.tv_gaming_console_disable");
        public IEntity ActiveMusicVoldown => _app.Entity("script.active_music_voldown");
        public IEntity BulkLaunchAc => _app.Entity("script.bulk_launch_ac");
        public IEntity SaveLastMovieState => _app.Entity("script.save_last_movie_state");
        public IEntity KodiPlaypause => _app.Entity("script.kodi_playpause");
        public IEntity BedroomPowerSaveOff => _app.Entity("script.bedroom_power_save_off");
        public IEntity AssistantDoactivityWatchtelevision => _app.Entity("script.assistant_doactivity_watchtelevision");
        public IEntity TvGamingConsoleEnable => _app.Entity("script.tv_gaming_console_enable");
        public IEntity Rl4mpPresetHigherright => _app.Entity("script.rl4mp_preset_higherright");
        public IEntity BedheadbackLoadpoint2 => _app.Entity("script.bedheadback_loadpoint2");
        public IEntity ActiveMusicVolup => _app.Entity("script.active_music_volup");
        public IEntity ArcadecabinetLoadpoint1 => _app.Entity("script.arcadecabinet_loadpoint1");
        public IEntity BulkLaunchSmartlamp => _app.Entity("script.bulk_launch_smartlamp");
        public IEntity KodiSetTvMode => _app.Entity("script.kodi_set_tv_mode");
        public IEntity DesktopGamingPcDisable => _app.Entity("script.desktop_gaming_pc_disable");
        public IEntity BulkLaunchTvNews => _app.Entity("script.bulk_launch_tv_news");
        public IEntity MopidyPrevious => _app.Entity("script.mopidy_previous");
        public IEntity NeonsignLoadpoint1 => _app.Entity("script.neonsign_loadpoint1");
        public IEntity AssistantDoactivityLeavehouse => _app.Entity("script.assistant_doactivity_leavehouse");
        public IEntity ArcadecabinetKill => _app.Entity("script.arcadecabinet_kill");
        public IEntity MopidyVolumeUp => _app.Entity("script.mopidy_volume_up");
        public IEntity Ac1ToggleAutoModeTablet => _app.Entity("script.ac1_toggle_auto_mode_tablet");
        public IEntity MopidyVolumeUpSinglestep => _app.Entity("script.mopidy_volume_up_singlestep");
        public IEntity SystemReboot => _app.Entity("script.system_reboot");
        public IEntity MopidyRemoveUnfavored => _app.Entity("script.mopidy_remove_unfavored");
        public IEntity Rl4mpHide => _app.Entity("script.rl4mp_hide");
        public IEntity Ac1Warm => _app.Entity("script.ac1_warm");
        public IEntity TogglePlaybackByProfile => _app.Entity("script.toggle_playback_by_profile");
        public IEntity HeadbackSunrise => _app.Entity("script.headback_sunrise");
        public IEntity ArcadecabinetMute => _app.Entity("script.arcadecabinet_mute");
        public IEntity Ac1ToggleByMode => _app.Entity("script.ac1_toggle_by_mode");
        public IEntity ActiveProfileVolumeUp => _app.Entity("script.active_profile_volume_up");
        public IEntity MediaPcKillGames => _app.Entity("script.media_pc_kill_games");
        public IEntity NeonsignSunrise => _app.Entity("script.neonsign_sunrise");
        public IEntity Ac2OffIr => _app.Entity("script.ac2_off_ir");
        public IEntity SonyProjectorPower => _app.Entity("script.sony_projector_power");
        public IEntity ClearPendingRequest => _app.Entity("script.clear_pending_request");
        public IEntity BulkLaunchLightString => _app.Entity("script.bulk_launch_light_string");
        public IEntity BulkLaunchFrontLight => _app.Entity("script.bulk_launch_front_light");
        public IEntity BedheadbackLoadpoint1 => _app.Entity("script.bedheadback_loadpoint1");
        public IEntity Ac1Hot => _app.Entity("script.ac1_hot");
        public IEntity Rl4mpLeft => _app.Entity("script.rl4mp_left");
        public IEntity BulkLaunchCandles => _app.Entity("script.bulk_launch_candles");
        public IEntity MediaPcScreenDesk => _app.Entity("script.media_pc_screen_desk");
        public IEntity RhasspyDoneactivitySleep => _app.Entity("script.rhasspy_doneactivity_sleep");
        public IEntity Speak => _app.Entity("script.speak");
        public IEntity ProfileCabletvUnpause => _app.Entity("script.profile_cabletv_unpause");
        public IEntity WakingUp => _app.Entity("script.waking_up");
        public IEntity SleepKeepMediaPcOn => _app.Entity("script.sleep_keep_media_pc_on");
        public IEntity MediaPcMuteToggle => _app.Entity("script.media_pc_mute_toggle");
        public IEntity BulkLaunchLightStringColor => _app.Entity("script.bulk_launch_light_string_color");
        public IEntity KodiUpdateLibrary => _app.Entity("script.kodi_update_library");
        public IEntity BulkLaunchInfinityCube => _app.Entity("script.bulk_launch_infinity_cube");
        public IEntity TvGamingConsoleDisableRecieverProcess => _app.Entity("script.tv_gaming_console_disable_reciever_process");
        public IEntity AutoLaunchTvCableProvider => _app.Entity("script.auto_launch_tv_cable_provider");
        public IEntity ArcadecabinetLoadpoint2 => _app.Entity("script.arcadecabinet_loadpoint2");
        public IEntity ProjectorEnable => _app.Entity("script.projector_enable");
        public IEntity SmartlampSavepoint2 => _app.Entity("script.smartlamp_savepoint2");
        public IEntity MopidyPlaylistConditionalShuffle => _app.Entity("script.mopidy_playlist_conditional_shuffle");
        public IEntity Ac1Off => _app.Entity("script.ac1_off");
        public IEntity NeonsignLoadpoint2 => _app.Entity("script.neonsign_loadpoint2");
        public IEntity ActiveKodiMusicReplay => _app.Entity("script.active_kodi_music_replay");
        public IEntity MopidyMarkUnfavored => _app.Entity("script.mopidy_mark_unfavored");
        public IEntity BulkLaunchBedHeadback => _app.Entity("script.bulk_launch_bed_headback");
        public IEntity ClearActiveProfile => _app.Entity("script.clear_active_profile");
        public IEntity ActivateProfileFromTarget => _app.Entity("script.activate_profile_from_target");
        public IEntity Rl4mpRight => _app.Entity("script.rl4mp_right");
        public IEntity TvGamingConsoleDisableTvProcess => _app.Entity("script.tv_gaming_console_disable_tv_process");
        public IEntity WakingUpAcProcess => _app.Entity("script.waking_up_ac_process");
        public IEntity Ac2NormalIr => _app.Entity("script.ac2_normal_ir");
        public IEntity UnpauseByActiveProfile => _app.Entity("script.unpause_by_active_profile");
        public IEntity MopidyStop => _app.Entity("script.mopidy_stop");
        public IEntity KodiPriSaveMovieState => _app.Entity("script.kodi_pri_save_movie_state");
        public IEntity LgtvVolumeDownSinglestep => _app.Entity("script.lgtv_volume_down_singlestep");
        public IEntity MopidyShufflePlay => _app.Entity("script.mopidy_shuffle_play");
        public IEntity InfinitycubeLoadpoint2 => _app.Entity("script.infinitycube_loadpoint2");
        public IEntity SonyProjectorLeft => _app.Entity("script.sony_projector_left");
        public IEntity TvPcDisable => _app.Entity("script.tv_pc_disable");
        public IEntity KodiPlaySelectionClear => _app.Entity("script.kodi_play_selection_clear");
        public IEntity MopidyShuffle => _app.Entity("script.mopidy_shuffle");
        public IEntity HouseLightThemeReading => _app.Entity("script.house_light_theme_reading");
        public IEntity SystemShutdown => _app.Entity("script.system_shutdown");
        public IEntity ProfileDisable => _app.Entity("script.profile_disable");
        public IEntity BulkLaunch => _app.Entity("script.bulk_launch");
        public IEntity Rl4mpUp => _app.Entity("script.rl4mp_up");
        public IEntity RhasspyAssistantUnmuteMedias => _app.Entity("script.rhasspy_assistant_unmute_medias");
        public IEntity InfinitycubeSleep => _app.Entity("script.infinitycube_sleep");
        public IEntity KodiPriNext => _app.Entity("script.kodi_pri_next");
        public IEntity TvCableProviderDisable => _app.Entity("script.tv_cable_provider_disable");
        public IEntity KodiPriLoadMovieState => _app.Entity("script.kodi_pri_load_movie_state");
        public IEntity InfinitycubeLoadpoint1 => _app.Entity("script.infinitycube_loadpoint1");
        public IEntity MediaPcConditionalOff => _app.Entity("script.media_pc_conditional_off");
        public IEntity SmartlampSavepoint1 => _app.Entity("script.smartlamp_savepoint1");
        public IEntity HassRestart => _app.Entity("script.hass_restart");
        public IEntity GoingToSleepForce => _app.Entity("script.going_to_sleep_force");
        public IEntity WakingUpBoilerProcess => _app.Entity("script.waking_up_boiler_process");
        public IEntity AssistantDoactivityUseCinemaInBackground => _app.Entity("script.assistant_doactivity_use_cinema_in_background");
        public IEntity ProjectorDisable => _app.Entity("script.projector_disable");
        public IEntity TvCableProviderEnable => _app.Entity("script.tv_cable_provider_enable");
        public IEntity BulkLaunchBackLight => _app.Entity("script.bulk_launch_back_light");
        public IEntity NeonsignSavepoint2 => _app.Entity("script.neonsign_savepoint2");
        public IEntity BedHeadbackColors => _app.Entity("script.bed_headback_colors");
        public IEntity Ac1ToggleByModeTablet => _app.Entity("script.ac1_toggle_by_mode_tablet");
        public IEntity MediaPcSleep => _app.Entity("script.media_pc_sleep");
        public IEntity Ac1Cold => _app.Entity("script.ac1_cold");
        public IEntity Ac1Cool => _app.Entity("script.ac1_cool");
        public IEntity LgtvVolumeUpSinglestep => _app.Entity("script.lgtv_volume_up_singlestep");
        public IEntity Testing => _app.Entity("script.testing");
        public IEntity SonyProjectorRight => _app.Entity("script.sony_projector_right");
        public IEntity GoingToSleep => _app.Entity("script.going_to_sleep");
        public IEntity AssistantDoactivityPctv => _app.Entity("script.assistant_doactivity_pctv");
        public IEntity BulkLaunchMusic => _app.Entity("script.bulk_launch_music");
        public IEntity HouseLightThemeEvening => _app.Entity("script.house_light_theme_evening");
        public IEntity ReceiverEntertainmentMode => _app.Entity("script.receiver_entertainment_mode");
        public IEntity AssistantDoactivityPlayconsole => _app.Entity("script.assistant_doactivity_playconsole");
        public IEntity SonyProjectorEnter => _app.Entity("script.sony_projector_enter");
        public IEntity Ac2Warm => _app.Entity("script.ac2_warm");
        public IEntity BedheadbackSavepoint2 => _app.Entity("script.bedheadback_savepoint2");
        public IEntity BedheadbackSavepoint1 => _app.Entity("script.bedheadback_savepoint1");
        public IEntity Ac2Fan => _app.Entity("script.ac2_fan");
        public IEntity ProjectorRestoreLightsStates => _app.Entity("script.projector_restore_lights_states");
        public IEntity BulkLaunchWarehouseLight => _app.Entity("script.bulk_launch_warehouse_light");
        public IEntity DesktopGamingPcEnable => _app.Entity("script.desktop_gaming_pc_enable");
        public IEntity Rl4mpDown => _app.Entity("script.rl4mp_down");
        public IEntity HouseLightThemeNight => _app.Entity("script.house_light_theme_night");
        public IEntity ArcadecabinetRestart => _app.Entity("script.arcadecabinet_restart");
        public IEntity MopidyVolumeDown => _app.Entity("script.mopidy_volume_down");
        public IEntity Ac1Fan => _app.Entity("script.ac1_fan");
        public IEntity Ac2ToggleByMode => _app.Entity("script.ac2_toggle_by_mode");
        public IEntity MopidyMarkFavored => _app.Entity("script.mopidy_mark_favored");
        public IEntity Ac1FanSetup => _app.Entity("script.ac1_fan_setup");
        public IEntity ProjectorPrepareLighting => _app.Entity("script.projector_prepare_lighting");
        public IEntity BulkLaunchArcadeCabinet => _app.Entity("script.bulk_launch_arcade_cabinet");
        public IEntity ProfileDisabledUnpause => _app.Entity("script.profile_disabled_unpause");
        public IEntity TvPcEnable => _app.Entity("script.tv_pc_enable");
        public IEntity Ac2ToggleAutoModeTablet => _app.Entity("script.ac2_toggle_auto_mode_tablet");
        public IEntity RhasspyAssistantMuteMedias => _app.Entity("script.rhasspy_assistant_mute_medias");
        public IEntity MopidyRestart => _app.Entity("script.mopidy_restart");
        public IEntity InfinitycubeSavepoint2 => _app.Entity("script.infinitycube_savepoint2");
        public IEntity Ac2Off => _app.Entity("script.ac2_off");
        public IEntity ProfileTvpcUnpause => _app.Entity("script.profile_tvpc_unpause");
        public IEntity ActiveProfileVolumeDown => _app.Entity("script.active_profile_volume_down");
        public IEntity BulkLaunchNeonSign => _app.Entity("script.bulk_launch_neon_sign");
        public IEntity ReceiverCheckPrepare => _app.Entity("script.receiver_check_prepare");
        public IEntity TurnOffPhilipsTvOnLaptopOff => _app.Entity("script.turn_off_philips_tv_on_laptop_off");
        public IEntity Ac2Cold => _app.Entity("script.ac2_cold");
        public IEntity ArcadecabinetSavepoint1 => _app.Entity("script.arcadecabinet_savepoint1");
        public IEntity MopidyVolumeDownSinglestep => _app.Entity("script.mopidy_volume_down_singlestep");
        public IEntity TvDisableLightingProcess => _app.Entity("script.tv_disable_lighting_process");
        public IEntity MediaPcClearMouse => _app.Entity("script.media_pc_clear_mouse");
        public IEntity KodiSetRecieverMode => _app.Entity("script.kodi_set_reciever_mode");
        public IEntity Ac2Cool => _app.Entity("script.ac2_cool");
        public IEntity AssistantDoactivitySleep => _app.Entity("script.assistant_doactivity_sleep");
        public IEntity MediaPcScreenTv => _app.Entity("script.media_pc_screen_tv");
        public IEntity ArcadecabinetSavepoint2 => _app.Entity("script.arcadecabinet_savepoint2");
        public IEntity SmartlampLoadpoint1 => _app.Entity("script.smartlamp_loadpoint1");
        public IEntity NetdaemonRestart => _app.Entity("script.netdaemon_restart");
        public IEntity ProfileDisabledPause => _app.Entity("script.profile_disabled_pause");
        public IEntity KodiStop => _app.Entity("script.kodi_stop");
        public IEntity HouseTurnOff => _app.Entity("script.house_turn_off");
        public IEntity KodiPriPauseOrStop => _app.Entity("script.kodi_pri_pause_or_stop");
        public IEntity Ac2Hot => _app.Entity("script.ac2_hot");
        public IEntity KodiPriPrevious => _app.Entity("script.kodi_pri_previous");
        public IEntity MopidyConditionalUnmute => _app.Entity("script.mopidy_conditional_unmute");
        public IEntity HouseLightThemeRomantic => _app.Entity("script.house_light_theme_romantic");
        public IEntity ProfileCabletvPause => _app.Entity("script.profile_cabletv_pause");
        public IEntity Ac2ToggleByModeTablet => _app.Entity("script.ac2_toggle_by_mode_tablet");
        public IEntity MediaPcCloseActiveWindow => _app.Entity("script.media_pc_close_active_window");
        public IEntity Rl4mpPresetMiddle => _app.Entity("script.rl4mp_preset_middle");
        public IEntity TvPcEnableRecieverProcess => _app.Entity("script.tv_pc_enable_reciever_process");
        public IEntity LcdToggle => _app.Entity("script.lcd_toggle");
        public IEntity HeadbackSleep => _app.Entity("script.headback_sleep");
        public IEntity PauseByActiveProfile => _app.Entity("script.pause_by_active_profile");
        public IEntity RhasspyAssistantWakeup => _app.Entity("script.rhasspy_assistant_wakeup");
        public IEntity TvEnableLightingProcess => _app.Entity("script.tv_enable_lighting_process");
        public IEntity BulkLaunchArcadeCabinetRgb => _app.Entity("script.bulk_launch_arcade_cabinet_rgb");
        public IEntity WakingUpForce => _app.Entity("script.waking_up_force");
        public IEntity LoadLastMovieState => _app.Entity("script.load_last_movie_state");
        public IEntity AssistantDoactivityUseCinema => _app.Entity("script.assistant_doactivity_use_cinema");
        public IEntity MopidyNext => _app.Entity("script.mopidy_next");
        public IEntity ProfileTvpcPause => _app.Entity("script.profile_tvpc_pause");
        public IEntity MediaPcScreenProjector => _app.Entity("script.media_pc_screen_projector");
    }

    public partial class MediaPlayerEntities
    {
        private readonly NetDaemonApp _app;
        public MediaPlayerEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public IMediaPlayer Eccef44127e0e6b2 => _app.MediaPlayer("media_player.eccef441_27e0e6b2");
        public IMediaPlayer E3c93d829A6a8fd92 => _app.MediaPlayer("media_player.3c93d829_a6a8fd92");
        public IMediaPlayer LivingRoomTv => _app.MediaPlayer("media_player.living_room_tv");
        public IMediaPlayer Mopidy => _app.MediaPlayer("media_player.mopidy");
        public IMediaPlayer E408fb272C9cfe7cd => _app.MediaPlayer("media_player.408fb272_c9cfe7cd");
        public IMediaPlayer LivingRoomTv2 => _app.MediaPlayer("media_player.living_room_tv_2");
        public IMediaPlayer KodiPrimary => _app.MediaPlayer("media_player.kodi_primary");
    }

    public partial class CameraEntities
    {
        private readonly NetDaemonApp _app;
        public CameraEntities(NetDaemonApp app)
        {
            _app = app;
        }

        public ICamera EyetoyWarehouse => _app.Camera("camera.eyetoy_warehouse");
        public ICamera E3dPrinterCamera => _app.Camera("camera.3d_printer_camera");
    }
}